---
engines:
  duplication:
    enabled: true
    config:
      languages:
        javascript:
          mass_threshold: 75
  eslint:
    enabled: true
  fixme:
    enabled: true
ratings:
  paths:
  - "**.js"
exclude_paths:
- test/
- node_modules/
- "API.md"
- "LICENSE"
- "README.md"
- "package.json"
exclude_fingerprints:
- f3b166b0a755f0ac4b5e91933417c0f8
- 76b539d0a7f961edfd85bd434c906aef
