env:
  browser: true
  commonjs: true
  node: true
  amd: true
extends: 'eslint:recommended'
rules:
  indent:
    - error
    - 2
  quotes:
    - warn
    - single
  semi:
    - error
    - always
  eqeqeq:
    - warn
    - smart
  valid-jsdoc:
    - warn
  no-unreachable:
    - error
  strict:
    - error
  no-trailing-spaces:
    - warn
